# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Holidays-FR
version:      0.02
version_from: lib/Date/Holidays/FR.pm
installdirs:  site
requires:
    Date::Easter:                  0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
